// Mocks generated by Mockito 5.2.0 from annotations
// in invola_assesment/test/features/course_details/data/data_source_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:invola_assesment/features/course_details/data/models/course_details_api_response.dart'
    as _i2;
import 'package:invola_assesment/features/course_details/data/service/course_details_api_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCourseDetailsApiResponse_0 extends _i1.Fake
    implements _i2.CourseDetailsApiResponse {}

/// A class which mocks [CourseDetailsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseDetailsApiService extends _i1.Mock
    implements _i3.CourseDetailsApiService {
  MockCourseDetailsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CourseDetailsApiResponse> getCourseDetails() =>
      (super.noSuchMethod(Invocation.method(#getCourseDetails, []),
              returnValue: Future<_i2.CourseDetailsApiResponse>.value(
                  _FakeCourseDetailsApiResponse_0()))
          as _i4.Future<_i2.CourseDetailsApiResponse>);
}
